# .github/workflows/tests.yml
name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8.8'
        architecture: x64
    - run: sudo apt-get install portaudio19-dev
    - run: pip install nox==2023.04.22
    - run: pip install poetry==1.1.9
    - run: nox
